POST http://localhost:5000/newuser
content-type: application/json

{
    "name": "neloy",
    "password": "password"
}

###

POST http://localhost:5000/login
content-type: application/json

{
    "name": "neloy",
    "password": "password"
}


###
POST http://localhost:5000/leaveparty
content-type: application/json 

{
    "partyHost" : "neloy" 
}

###
GET http://localhost:5000/getjoinstatus
content-type: application/json

{
    
}

GET "https://api.spotify.com/v1/search/q=\(finalizedQuery)&type=track&limit=1"
content-type: application/json
Authorization: 